#!/usr/bin/env bash

set -euo pipefail

function green() {
    text="${1:- }"
    echo -e "\n\033[32m$text\033[0m"
}
function printg() {
    text="${1:- }"
    echo -e "\n\033[35m$text \033[0m"
}
function print() {
    text="${1:- }"
    echo -e "\n\033[32m$text  \033[0m"
}

green "Deploying in  ENV=${ENVIRONMENT}"
: "${ENVIRONMENT:?You must specify a ENVIRONMENT variable}"

